language: python
sudo: false
cache:
  directories:
  - eggs
  - downloads
python:
  - 2.7
matrix:
  fast_finish: true
dist: xenial
services:
  - xvfb
install:
  - python bootstrap-buildout.py
  - bin/buildout -N buildout:download-cache=downloads annotate
  - bin/buildout -N buildout:download-cache=downloads
before_script:
- firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
notifications:
  email:
    - brian.duncan@wildcardcorp.com
